### ISSUE TITLE
Commercetools performance optimization TODO

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/next#266]
- [ ] Make off-screen components loaded lazily (cart, login modal) which will end up in loading composables lazily as well (minor improvement)
- [ ] Group checkout-related api client methods in a separate chunk (minor improvement)
- [ ] Serve images in next-gen format (2s saving)
- [ ] Get rid of prismic from the main bundle (30 kB gzipped)
- [ ] Include wee-validate on demand with forms (10 kb gzipped)
